version: 0.1

phases:
  install:
    commands:
      - echo Installing Python requirements
      - pip3 install -U pip
      - pip3 install -r requirements.txt -t env/python/lib/python3.8/site-packages/
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:  
    type: zip
    files:
        - '**/*'
    secondary-artifacts:
      app:
        files:
          - '**/*'
        base-directory: app
        discard-paths: no
        name: app
      infra:
        files:
          - '**/*'
        base-directory: infra
        discard-paths: yes
        name: infra
      layer:
        files:
          - './**/*'
        base-directory: env
        discard-paths: no
        name: layer